services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: eleicao-kafka
    ports:
      - "9092:9092"
    environment:
      # Modo KRaft (sem ZooKeeper)
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/bitnami/kafka

  mongo:
    image: mongo:7
    container_name: eleicao-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # UI opcional para inspecionar o MongoDB: http://localhost:8081
  mongo-express:
    image: mongo-express:1.0.2
    container_name: eleicao-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  kafka_data:
  mongo_data:
